package Entidad;
// Generated 01/12/2019 10:14:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bus generated by hbm2java
 */
@Entity
@Table(name="bus"
    ,catalog="transporte"
)
public class Bus  implements java.io.Serializable {


     private Integer idBus;
     private String placa;
     private int asientos;
     private Set pasajeses = new HashSet(0);

    public Bus() {
    }

	
    public Bus(String placa, int asientos) {
        this.placa = placa;
        this.asientos = asientos;
    }
    public Bus(String placa, int asientos, Set pasajeses) {
       this.placa = placa;
       this.asientos = asientos;
       this.pasajeses = pasajeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_bus", unique=true, nullable=false)
    public Integer getIdBus() {
        return this.idBus;
    }
    
    public void setIdBus(Integer idBus) {
        this.idBus = idBus;
    }

    
    @Column(name="placa", nullable=false, length=8)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

    
    @Column(name="asientos", nullable=false)
    public int getAsientos() {
        return this.asientos;
    }
    
    public void setAsientos(int asientos) {
        this.asientos = asientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bus")
    public Set getPasajeses() {
        return this.pasajeses;
    }
    
    public void setPasajeses(Set pasajeses) {
        this.pasajeses = pasajeses;
    }




}


