package Entidad;
// Generated 01/12/2019 10:14:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,catalog="transporte"
)
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private String departamentoNombre;
     private Set provincias = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento, String departamentoNombre) {
        this.idDepartamento = idDepartamento;
        this.departamentoNombre = departamentoNombre;
    }
    public Departamento(int idDepartamento, String departamentoNombre, Set provincias) {
       this.idDepartamento = idDepartamento;
       this.departamentoNombre = departamentoNombre;
       this.provincias = provincias;
    }
   
     @Id 

    
    @Column(name="id_departamento", unique=true, nullable=false)
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    
    @Column(name="departamento_nombre", nullable=false, length=250)
    public String getDepartamentoNombre() {
        return this.departamentoNombre;
    }
    
    public void setDepartamentoNombre(String departamentoNombre) {
        this.departamentoNombre = departamentoNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set provincias) {
        this.provincias = provincias;
    }




}


