package Entidad;
// Generated 01/12/2019 10:14:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Distrito generated by hbm2java
 */
@Entity
@Table(name="distrito"
    ,catalog="transporte"
)
public class Distrito  implements java.io.Serializable {


     private int idDistrito;
     private Provincia provincia;
     private String distritoNombre;
     private Set clientes = new HashSet(0);

    public Distrito() {
    }

	
    public Distrito(int idDistrito, Provincia provincia, String distritoNombre) {
        this.idDistrito = idDistrito;
        this.provincia = provincia;
        this.distritoNombre = distritoNombre;
    }
    public Distrito(int idDistrito, Provincia provincia, String distritoNombre, Set clientes) {
       this.idDistrito = idDistrito;
       this.provincia = provincia;
       this.distritoNombre = distritoNombre;
       this.clientes = clientes;
    }
   
     @Id 

    
    @Column(name="id_distrito", unique=true, nullable=false)
    public int getIdDistrito() {
        return this.idDistrito;
    }
    
    public void setIdDistrito(int idDistrito) {
        this.idDistrito = idDistrito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_provincia", nullable=false)
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }

    
    @Column(name="distrito_nombre", nullable=false, length=250)
    public String getDistritoNombre() {
        return this.distritoNombre;
    }
    
    public void setDistritoNombre(String distritoNombre) {
        this.distritoNombre = distritoNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="distrito")
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


