package Entidad;
// Generated 01/12/2019 10:14:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pasajes generated by hbm2java
 */
@Entity
@Table(name="pasajes"
    ,catalog="transporte"
)
public class Pasajes  implements java.io.Serializable {


     private Integer idPasaje;
     private Bus bus;
     private Rutas rutas;
     private String asiento;
     private Date fechaPartida;
     private Date fechaLlegada;
     private double total;
     private String dni;

    public Pasajes() {
    }

    public Pasajes(Bus bus, Rutas rutas, String asiento, Date fechaPartida, Date fechaLlegada, double total, String dni) {
       this.bus = bus;
       this.rutas = rutas;
       this.asiento = asiento;
       this.fechaPartida = fechaPartida;
       this.fechaLlegada = fechaLlegada;
       this.total = total;
       this.dni = dni;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_pasaje", unique=true, nullable=false)
    public Integer getIdPasaje() {
        return this.idPasaje;
    }
    
    public void setIdPasaje(Integer idPasaje) {
        this.idPasaje = idPasaje;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_bus", nullable=false)
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ruta", nullable=false)
    public Rutas getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Rutas rutas) {
        this.rutas = rutas;
    }

    
    @Column(name="asiento", nullable=false, length=5)
    public String getAsiento() {
        return this.asiento;
    }
    
    public void setAsiento(String asiento) {
        this.asiento = asiento;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_partida", nullable=false, length=19)
    public Date getFechaPartida() {
        return this.fechaPartida;
    }
    
    public void setFechaPartida(Date fechaPartida) {
        this.fechaPartida = fechaPartida;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_llegada", nullable=false, length=19)
    public Date getFechaLlegada() {
        return this.fechaLlegada;
    }
    
    public void setFechaLlegada(Date fechaLlegada) {
        this.fechaLlegada = fechaLlegada;
    }

    
    @Column(name="total", nullable=false, precision=22, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

    
    @Column(name="dni", nullable=false, length=5)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }




}


