package Entidad;
// Generated 01/12/2019 10:14:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="provincia"
    ,catalog="transporte"
)
public class Provincia  implements java.io.Serializable {


     private int idProvincia;
     private Departamento departamento;
     private String provinciaNombre;
     private Set distritos = new HashSet(0);
     private Set rutasesForPartida = new HashSet(0);
     private Set rutasesForDestino = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(int idProvincia, Departamento departamento, String provinciaNombre) {
        this.idProvincia = idProvincia;
        this.departamento = departamento;
        this.provinciaNombre = provinciaNombre;
    }
    public Provincia(int idProvincia, Departamento departamento, String provinciaNombre, Set distritos, Set rutasesForPartida, Set rutasesForDestino) {
       this.idProvincia = idProvincia;
       this.departamento = departamento;
       this.provinciaNombre = provinciaNombre;
       this.distritos = distritos;
       this.rutasesForPartida = rutasesForPartida;
       this.rutasesForDestino = rutasesForDestino;
    }
   
     @Id 

    
    @Column(name="id_provincia", unique=true, nullable=false)
    public int getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(int idProvincia) {
        this.idProvincia = idProvincia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_departamento", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="provincia_nombre", nullable=false, length=250)
    public String getProvinciaNombre() {
        return this.provinciaNombre;
    }
    
    public void setProvinciaNombre(String provinciaNombre) {
        this.provinciaNombre = provinciaNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provincia")
    public Set getDistritos() {
        return this.distritos;
    }
    
    public void setDistritos(Set distritos) {
        this.distritos = distritos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provinciaByPartida")
    public Set getRutasesForPartida() {
        return this.rutasesForPartida;
    }
    
    public void setRutasesForPartida(Set rutasesForPartida) {
        this.rutasesForPartida = rutasesForPartida;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provinciaByDestino")
    public Set getRutasesForDestino() {
        return this.rutasesForDestino;
    }
    
    public void setRutasesForDestino(Set rutasesForDestino) {
        this.rutasesForDestino = rutasesForDestino;
    }




}


