package Entidad;
// Generated 01/12/2019 10:14:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rutas generated by hbm2java
 */
@Entity
@Table(name="rutas"
    ,catalog="transporte"
)
public class Rutas  implements java.io.Serializable {


     private Integer idRuta;
     private Provincia provinciaByPartida;
     private Provincia provinciaByDestino;
     private double precio;
     private Set pasajeses = new HashSet(0);

    public Rutas() {
    }

	
    public Rutas(Provincia provinciaByPartida, Provincia provinciaByDestino, double precio) {
        this.provinciaByPartida = provinciaByPartida;
        this.provinciaByDestino = provinciaByDestino;
        this.precio = precio;
    }
    public Rutas(Provincia provinciaByPartida, Provincia provinciaByDestino, double precio, Set pasajeses) {
       this.provinciaByPartida = provinciaByPartida;
       this.provinciaByDestino = provinciaByDestino;
       this.precio = precio;
       this.pasajeses = pasajeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_ruta", unique=true, nullable=false)
    public Integer getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(Integer idRuta) {
        this.idRuta = idRuta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="partida", nullable=false)
    public Provincia getProvinciaByPartida() {
        return this.provinciaByPartida;
    }
    
    public void setProvinciaByPartida(Provincia provinciaByPartida) {
        this.provinciaByPartida = provinciaByPartida;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="destino", nullable=false)
    public Provincia getProvinciaByDestino() {
        return this.provinciaByDestino;
    }
    
    public void setProvinciaByDestino(Provincia provinciaByDestino) {
        this.provinciaByDestino = provinciaByDestino;
    }

    
    @Column(name="precio", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rutas")
    public Set getPasajeses() {
        return this.pasajeses;
    }
    
    public void setPasajeses(Set pasajeses) {
        this.pasajeses = pasajeses;
    }




}


